modLoader = "javafml"
loaderVersion = "[43,)"
license = "All Rights Reserved"
[[mods]]
    modId = "mobitems"
    version = "${file.jarVersion}"
    displayName = "mobitems"
    authors = "BobVarioa"
    description = '''

    '''
[[dependencies.mobitems]]
    modId = "forge"
    mandatory = true
    versionRange = "[43,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.mobitems]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.2,1.20)"
    ordering = "NONE"
    side = "BOTH"
